name: peatfr_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas>=2.0
  - numpy>=1.24
  - scikit-learn>=1.3
  - scipy>=1.11
  - statsmodels>=0.14
  - matplotlib>=3.7
  - pmdarima>=2.0.4
  - pyqt=6
  # --- Sisanya via pip ---
  - pip:
      - "fastapi>=0.110.0"
      - "uvicorn[standard]>=0.27.0"
      - python-multipart>=0.0.9
      - python-dotenv>=1.0.0
      - PyQt6>=6.6.0
      - requests>=2.31.0
      - openpyxl>=3.1.0
      - "python-jose[cryptography]>=3.3.0"
      - passlib[bcrypt]==1.7.4
      - bcrypt==4.0.1
      - Deep Learning
      - tensorflow>=2.15
      - torch>=2.0 